[channel]
generator = utipod
xmlbase = http://174.89.233.32:8080/UCribHdOMgiD5R3OUDgx2qTg
title = "netdevconf"
link = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
description = "Netdev Conference Videos"

[channel "image"]
url = https://yt3.ggpht.com/vTMioni_IhhZU4G_Xcz22Q2XsNMgMW3FtlLmYIVO33UGPhFOAVjChaqqyw56AUJ-s5qrim7ttQ=s0

