[item]
guid = 0dks4mys0-k
title = "Netdev 0x15 - Syrup: User Defined Scheduling Across the Stack"
description = "Speakers:\nKostis Kaffes\nJack Tigar Humphries\nDavid Mazières\nChristos Kozyrakis\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?Syrup:-User-Defined-Scheduling-Across-the-Stack"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=0dks4mys0-k
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = 0dks4mys0-k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/0dks4mys0-k/hqdefault.jpg

