[item]
guid = 6mfA6WCakr0
title = "Netdev 0x15 - IoT Networking Workshop"
description = "Chair: Stefan Schmidt\n\nSession Type: Workshop\n\nInfo: https://netdevconf.info/0x15/session.html?IoT-Networking-Workshop"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=6mfA6WCakr0
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = 6mfA6WCakr0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/6mfA6WCakr0/sddefault.webp

