[item]
guid = _8R1MYP7M48
title = "Netdev 0x15 - FRR Workshop"
description = "Chairs:\nDonald Sharp\nStephen Worley\n\nSession Type: Workshop\n\nInfo: https://netdevconf.info/0x15/session.html?FRR-Workshop"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=_8R1MYP7M48
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = _8R1MYP7M48.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/_8R1MYP7M48/sddefault.webp

