[item]
guid = auen1MpxxGY
title = "Netdev 0x15 - ghOST Fast & Flexible User Space Delegation of Linux Scheduling"
description = "Speakers:\nJack Tigar Humphries\nNeel Natu\nAshwin Chaugule\nOfir Weisse\nBarret Rhoden\nJosh Don\nLuigi Rizzo\nOleg Rombakh\nPaul Turner\nChristos Kozyrakis\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?ghOSt:-Fast-&-Flexible-User-Space-Delegation-of-Linux-Scheduling"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=auen1MpxxGY
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = auen1MpxxGY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/auen1MpxxGY/hqdefault.jpg

