[item]
guid = EceQhoYcdkw
title = "Netdev 0x15 - Tutorial: Introduction to time synchronization over Ethernet"
description = "Instructor: Maciej Machnikowski\n\nSession Type: Tutorial\n\nInfo: https://netdevconf.info/0x15/session.html?Introduction-to-time-synchronization-over-Ethernet"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=EceQhoYcdkw
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = EceQhoYcdkw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/EceQhoYcdkw/hqdefault.jpg

