[item]
guid = gonPoiKYHoc
title = "Netdev 0x15 - Switchdev Offload Workshop"
description = "Chairs:\nRoopa Prabhu\nJiri Pirko\n\n\nSession Type: Workshop\n\nInfo: https://netdevconf.info/0x15/session.html?Switchdev-Offload-Workshop"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=gonPoiKYHoc
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = gonPoiKYHoc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/gonPoiKYHoc/sddefault.webp

