[item]
guid = HDkA2o-TzlI
title = "Netdev 0x15 - Autonomous NVMe TCP offload"
description = "Speakers:\nBoris Pismenny\nYoray Zack\nBen Ben-Ishay\nOr Gerlitz\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?Autonomous-NVMe-TCP-offload"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=HDkA2o-TzlI
category = "Science & Technology"
pubdate = Wed, 01 Sep 2021 00:00:00 -0000
enclosure = HDkA2o-TzlI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/HDkA2o-TzlI/sddefault.webp

