[item]
guid = OROFNACMxbc
title = "Netdev 0x15 - BIG TCP"
description = "Speaker: Eric Dumazet\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?BIG-TCP"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=OROFNACMxbc
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = OROFNACMxbc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/OROFNACMxbc/hqdefault.jpg

