[item]
guid = q5nFZSBh9_k
title = "Netdev 0x15 - Netfilter Mini Workshop"
description = "Chair: Florian Westphal\n\nSession Type: Workshop\n\nInfo: https://netdevconf.info/0x15/session.html?Netfilter-Mini-Workshop"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=q5nFZSBh9_k
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = q5nFZSBh9_k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/q5nFZSBh9_k/sddefault.webp

