[item]
guid = UCUtudQ33Pc
title = "Netdev 0x13 -  Paced Chirping   Rethinking TCP start up"
description = "Joakim Misund and Bob Briscoe talk about Paced Chirping.\n\nTCP slow start faces a dilemma: Either you take too long to ramp up or you ramp up too fast\nand cause significant queuing delays.  Paced Chirping gets a flow to achieve\nfast acceleration with virtually no queuing delay\n\nThe implementation extends the kernel's pacing framework to allow a congestion control\nmodule to create "chirps" with desired characteristics. Bob describes\nthe implementation and how one would use the extensions.\n\nMore info:\nhttps://netdevconf.org/0x13/news.html?talk-chirp"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=UCUtudQ33Pc
category = "Science & Technology"
pubdate = Sun, 26 May 2019 00:00:00 -0000
enclosure = UCUtudQ33Pc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/UCUtudQ33Pc/maxresdefault.webp

