[item]
guid = x-LAidU27r0
title = "Netdev 0x15 - Precision Time Protocol Optimization Using Genetic Algorithm"
description = "Speakers:\nMarta A Plantykow\nMilena Olech\nMaciej Machnikowski\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?Precision-Time-Protocol-optimization-using-genetic-algorithm"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=x-LAidU27r0
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = x-LAidU27r0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/x-LAidU27r0/hqdefault.jpg

