[item]
guid = x4mLzhkmKHE
title = "Netdev 0x15 - Dynamic Interface Power Management (PowerMAN)"
description = "Speakers:\nJesse Brandeburg\nBrett Creeley\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?Dynamic-Interface-Power-Management-(PowerMAN)"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=x4mLzhkmKHE
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = x4mLzhkmKHE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/x4mLzhkmKHE/sddefault.webp

