[item]
guid = XES3bO2rW14
title = "Netdev 0x15 - Accelerating synproxy with XDP"
description = "Speaker: Maxim Mikityanskiy\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?Accelerating-synproxy-with-XDP"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=XES3bO2rW14
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = XES3bO2rW14.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/XES3bO2rW14/sddefault.webp

