[item]
guid = zVnmVDSEoXc
title = "Netdev 0x15 - Replacing Flow Dissector with PANDA Parser"
description = "Speaker: Tom A Herbert\n\nSession Type: Talk\n\nInfo: https://netdevconf.info/0x15/session.html?Replacing-Flow-Dissector-with-PANDA-Parser"
author = netdevconf
source = https://www.youtube.com/channel/UCribHdOMgiD5R3OUDgx2qTg
link = https://www.youtube.com/watch?v=zVnmVDSEoXc
category = "Science & Technology"
pubdate = Tue, 31 Aug 2021 00:00:00 -0000
enclosure = zVnmVDSEoXc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/zVnmVDSEoXc/sddefault.webp

